### ISSUE TITLE
v1.17 binaries missing from Releases/Stable

### ISSUE THREAD

**Issue by Kriechi** [dc42/PanelDueFirmware#10]
1.17 seems to be final now, however, https://github.com/dc42/PanelDueFirmware/tree/master/Release/Stable only contains 1.16 binaries. 

@dc42 do you plan on putting the files there as well, or is https://github.com/dc42/PanelDueFirmware/releases the future?

**Comment by dc42** [comment]
Please use the Releases link.

On 2 September 2017 23:52:08 CEST, Thomas Kriechbaumer <notifications@github.com> wrote:
>1.17 seems to be final now, however,
>https://github.com/dc42/PanelDueFirmware/tree/master/Release/Stable
>only contains 1.16 binaries. 
>
>@dc42 do you plan on putting the files there as well, or is
>https://github.com/dc42/PanelDueFirmware/releases the future?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dc42/PanelDueFirmware/issues/10

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
