### ISSUE TITLE
Post build steps not executing

### ISSUE THREAD

**Issue by jpatrick-09** [dc42/PanelDueFirmware#19]
I've downloaded the latest files and when I build it within Eclipse, the project builds fine, and I am left with the .elf and .map files, however the .bin file is not being generated. I am using the 2017-q2-update of the arm toolkit. Do I need to change the post-build steps code for it to work with arm toolkit?  My current post build script is : arm-none-eabi-objcopy -O binary ${workspace_loc:/${ProjName}/${ConfigName}}/${BuildArtifactFileBaseName}.elf ${workspace_loc:/${ProjName}/${ConfigName}}/${BuildArtifactFileBaseName}.bin

Any help is appreciated!

**Comment by dc42** [comment]
There appears to be an intermittent bug in Eclipse when paths of that form are expanded. Try changing the first parameter to:

${workspace_loc}:/${ProjName}/${ConfigName}/${BuildArtifactFileBaseName}.elf

and make a similar change to the second one.

**Comment by jpatrick-09** [comment]
That didn't seem to work, I copied the code and made the same changes to both parameters, and got the same result. Any other ideas?

**Comment by dc42** [comment]
What was displayed in the CDT build console?

**Comment by jpatrick-09** [comment]
[Console output.txt](https://github.com/dc42/PanelDueFirmware/files/1797132/Console.output.txt)
Here is the console file. I don't see any reference to the post build script in the console at all. Thanks for your help.

**Comment by jpatrick-09** [comment]
I figured it out! The issue was I had parallel build enabled in the C++ build settings. Once I disabled that, it generated the .bin as expected. Thanks for the assistance.

**Comment by dc42** [comment]
Interesting! I have parallel build enabled too and the postbuild step works for me. Are you any any chance using the internal builder?

**Comment by jpatrick-09** [comment]
That is correct, I am currently using the internal builder. Is it more advantageous to use an external builder?

**Comment by dc42** [comment]
I've no idea, I only use an external builder (make) because that's how my original system was set up.

Looks like it is a known bug, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=199758.
