### ISSUE TITLE
Splashscreen

### ISSUE THREAD

**Issue by vignesh141292** [dc42/PanelDueFirmware#2]
Hi,

I like the latest firmware, it was easy to build and the STOP button was really useful.

I wanted to know if I can add a splashscreen with the company Logo? Can you guide me on the steps to add it.

Thanks

**Comment by chandler767** [comment]
I created a version of this firmware for [Fusion3 F400 printers](https://www.fusion3design.com/) that implements a splash screen with a logo image and a progress bar. You can see how I did it here:
https://github.com/chandler767/FusionPanel/blob/4554400cc050552d439745b32a2cc29e31e9a395/src/PanelDue.cpp#L1212

**Comment by jpatrick-09** [comment]
Chandler767: What tool are you using to convert the images into arrays?

**Comment by chandler767** [comment]
@jpatrick-09 I recommend using [ImageMagick](https://www.imagemagick.org/script/index.php).

[Convert a PNG image to a C++ Array](https://www.imagemagick.org/discourse-server/viewtopic.php?t=30421)

**Comment by dc42** [comment]
I'm using a patched version of bmp2c. I haven't had time do a proper fork of the project and publish it yet.

**Comment by paboman** [comment]
How to make my own splash screen on boot ?

**Comment by dc42** [comment]
Instructions are now included n the readme file.
