### ISSUE TITLE
Feature Request - Coordinates on the Move Screen

### ISSUE THREAD

**Issue by ccavanaugh** [dc42/PanelDueFirmware#26]
It would be very helpful if the coordinates were visible on the Move screen.  Usage would be manual tramming of the bed, testing limits, etc.

**Comment by zafuquazar** [comment]
I agree with this request wholeheartedly!

**Comment by dc42** [comment]
Added to the work list for consideration. the main concern is whether there is room, especially when additional axes are configured.

**Comment by Kriechi** [comment]
see #43
