### ISSUE TITLE
Latest firmware release won't flash

### ISSUE THREAD

**Issue by ccavanaugh** [dc42/PanelDueFirmware#4]
I'm trying to flash the latest PanelDue-7.0.bin and get an error from bossac "file operation exceeds flash size"

It flashes correctly with  PanelDue-7.0-1.15c.bin

**Comment by dc42** [comment]
Is this a binary that you built yourself? If so, how large is it? The maximum size is 128Kb for the standard version of PanelDue, although we have an OEM version with more flash memory.

**Comment by ccavanaugh** [comment]
This was downloaded from Github.   I downloaded as a zip file just to be certain the binary wasn't munged up by the browser.   I has also tried using bossac on Windows and Linux and received the same error.

Github download is reporting a 131,176 byte file size or 128.1Kb assuming 1024 bytes per Kb

**Comment by dc42** [comment]
The binaries you should be using are here https://github.com/dc42/PanelDueFirmware/tree/master/Release/Edge and the 7" version is 130728 bytes long.

**Comment by ccavanaugh** [comment]
Will try with the Edge release...  I used the binary in the Stable release folder which is 131,176 bytes.

Thanks!

**Comment by dc42** [comment]
Thanks, I've removed those over-sized binaries now.
